#base image
FROM node:8
#set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

#add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH
#install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g @angular/cli@1.7.1

#add app
COPY . /usr/src/app

#start app
# we don't have port settings in webpack.config.js file we mentioned port and host everything, if we have 
#these in webpack.config.js then no need to mention it here.
CMD webpack-dev-server --host 0.0.0.0 --port 8182